package org.enlaza.myapp;

import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Container;
import com.codename1.ui.Label;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form(BoxLayout.y());
        
        Container rowBotonera = new Container(BoxLayout.x());
        Container rowPeliculas = new Container(BoxLayout.x());
        Container peliculaFirst = new Container(BoxLayout.y());
        Container peliculaSecond = new Container(BoxLayout.y());
        Button buttonAdministracion = new Button("Administración");
        Button buttonClientes = new Button("Clientes");
        Button buttonPeliculas = new Button("Películas");
        Button buttonAlquileres = new Button("Alquileres");
        Label mulan = new Label(theme.getImage("mulan.jpg"));
        Label labelMulan = new Label("Mulán");
        Label thor = new Label(theme.getImage("thor.jpg"));
        Label labelThor = new Label("Thor");
        
        rowBotonera.add(buttonClientes);
        rowBotonera.add(buttonPeliculas);
        rowBotonera.add(buttonAlquileres);
        peliculaFirst.add(mulan);
        peliculaFirst.add(labelMulan);
        peliculaSecond.add(thor);
        peliculaSecond.add(labelThor);
        rowPeliculas.add(peliculaFirst);
        rowPeliculas.add(peliculaSecond);
        hi.add(buttonAdministracion);
        hi.add(rowBotonera);
        hi.add(rowPeliculas);
        
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
